name: ieccompiler
version: 0.1.0.0
github: "david9991/ieccompiler"
license: BSD3
author: "David <mail@wud.me>"
maintainer: "mail@wud.me"
copyright: "2025 David"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/david9991/ieccompiler#readme>

dependencies:
  - base
  - parsec
  - containers
  - pretty-tree
  - regex-base
  - regex-posix
  - regex-compat
  - llvm-hs-pure
  - ieee754
  - mtl
  - bytestring
  - text
  - llvm-hs-pretty
  - bytestring
  - websockets
  - strings
  - directory
  - free
  - indexed-traversable

library:
  source-dirs: src

executables:
  ieccompiler-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -W
    dependencies:
      - ieccompiler

tests:
  ieccompiler-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -W
    dependencies:
      - ieccompiler
